// <auto-generated />
using System;
using AppNamoro.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppNamoroLele.Migrations
{
    [DbContext(typeof(AppNamoroDbContext))]
    [Migration("20250721183040_AddPasswordOnUser")]
    partial class AddPasswordOnUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppNamoro.Models.Match", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MyMatchesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeoplesMatchesID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("MyMatchesID");

                    b.HasIndex("PeoplesMatchesID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("AppNamoro.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AppNamoro.Models.Match", b =>
                {
                    b.HasOne("AppNamoro.Models.User", "MyMatches")
                        .WithMany("MyMatches")
                        .HasForeignKey("MyMatchesID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppNamoro.Models.User", "PeoplesMatches")
                        .WithMany("PeoplesMatches")
                        .HasForeignKey("PeoplesMatchesID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MyMatches");

                    b.Navigation("PeoplesMatches");
                });

            modelBuilder.Entity("AppNamoro.Models.User", b =>
                {
                    b.Navigation("MyMatches");

                    b.Navigation("PeoplesMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
